name: ZetaTestCI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches:
      - master
      - develop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  zeta_test_job:
    runs-on: ubuntu-latest
    name: Testing zeta
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Building docker image and testing
        uses: ./ 
